# Generated by Django 3.0.7 on 2021-01-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
