# Generated by Django 3.0.7 on 2020-12-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201226_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='cindition',
            new_name='condition',
        ),
    ]
